/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx}", "./components/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#434843",
        "warm-clay": "#B7791F",
        "surface-container-lowest": "#ffffff",
        background: "#f7fafc",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "tertiary-fixed": "#d8e3fa",
        "on-secondary-fixed-variant": "#653e00",
        "primary-container": "#1b3022",
        "surface-container-low": "#f1f4f6",
        "on-secondary-fixed": "#2a1700",
        "tertiary-fixed-dim": "#bcc7dd",
        "on-error": "#ffffff",
        "surface-bright": "#f7fafc",
        "primary-fixed": "#d0e9d4",
        primary: "#061b0e",
        "surface-container": "#ebeef0",
        "secondary-container": "#feb557",
        "outline-variant": "#c3c8c1",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#8893a8",
        "soft-sand": "#F7FAFC",
        "on-primary-fixed": "#0b2013",
        "deep-forest": "#1B3022",
        secondary: "#855300",
        "on-secondary": "#ffffff",
        tertiary: "#0c1728",
        "tertiary-container": "#212c3d",
        "surface-container-high": "#e5e9eb",
        "on-tertiary-fixed": "#111c2c",
        "inverse-on-surface": "#eef1f3",
        "surface-tint": "#4d6453",
        "on-tertiary-fixed-variant": "#3c475a",
        "heritage-blue": "#01678B",
        "on-secondary-container": "#734700",
        "inverse-primary": "#b4cdb8",
        "ochre-earth": "#D6A170",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#181c1e",
        "on-background": "#181c1e",
        "on-primary": "#ffffff",
        outline: "#737973",
        "primary-fixed-dim": "#b4cdb8",
        "surface-dim": "#d7dadc",
        "slate-stone": "#4A5568",
        "secondary-fixed-dim": "#ffb95f",
        "on-primary-fixed-variant": "#364c3c",
        "surface-variant": "#e0e3e5",
        "inverse-surface": "#2d3133",
        surface: "#f7fafc",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#819986",
        "secondary-fixed": "#ffddb8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "max-width": "1280px",
        gutter: "24px",
        base: "8px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "display-lg-mobile": ["Playfair Display", "serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
      },
      fontSize: {
        "display-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
